# Generated by Django 3.0.2 on 2020-04-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.EmailField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('Mobno', models.CharField(max_length=14)),
                ('Profile_pic', models.ImageField(upload_to='profile')),
            ],
        ),
        migrations.AlterField(
            model_name='favourites',
            name='User_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Users'),
        ),
        migrations.AlterField(
            model_name='message',
            name='Receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='backend.Users'),
        ),
        migrations.AlterField(
            model_name='message',
            name='Sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='backend.Users'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Users'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
