# Generated by Django 3.0.2 on 2020-04-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200409_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(null=True, upload_to='productimg'),
        ),
        migrations.AlterField(
            model_name='product_img',
            name='Product_images',
            field=models.ImageField(upload_to='productimg/caraousel'),
        ),
    ]
