# Generated by Django 3.0.2 on 2020-04-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200413_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='registered_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='Profile_pic',
            field=models.ImageField(null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
