# Generated by Django 3.0.2 on 2020-04-19 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200413_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_img',
            name='Product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Product'),
        ),
    ]
