# Generated by Django 3.0.2 on 2020-04-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200419_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_img',
            name='Product_images',
        ),
        migrations.RemoveField(
            model_name='product_img',
            name='id',
        ),
        migrations.AddField(
            model_name='product_img',
            name='Product_images0',
            field=models.ImageField(null=True, upload_to='productimg/caraousel'),
        ),
        migrations.AddField(
            model_name='product_img',
            name='Product_images1',
            field=models.ImageField(null=True, upload_to='productimg/caraousel'),
        ),
        migrations.AddField(
            model_name='product_img',
            name='Product_images2',
            field=models.ImageField(null=True, upload_to='productimg/caraousel'),
        ),
        migrations.AddField(
            model_name='product_img',
            name='Product_images3',
            field=models.ImageField(null=True, upload_to='productimg/caraousel'),
        ),
        migrations.AddField(
            model_name='product_img',
            name='Product_images4',
            field=models.ImageField(null=True, upload_to='productimg/caraousel'),
        ),
        migrations.AddField(
            model_name='product_img',
            name='Product_images5',
            field=models.ImageField(null=True, upload_to='productimg/caraousel'),
        ),
        migrations.AddField(
            model_name='product_img',
            name='Product_images6',
            field=models.ImageField(null=True, upload_to='productimg/caraousel'),
        ),
        migrations.AddField(
            model_name='product_img',
            name='Product_images7',
            field=models.ImageField(null=True, upload_to='productimg/caraousel'),
        ),
        migrations.AlterField(
            model_name='product_img',
            name='Product_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
