# Generated by Django 3.0.2 on 2020-04-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='profilepix',
        ),
    ]
